codestates-seb/seb40_main_017

server/src/main/java/team017/ServerApplication.java

- Application Class에 @SpringBootApplication Annotation을 추가하였습니다.

#4 add: add annotation

---

server/src/main/java/team017/ServerApplication.java
server/src/main/java/team017/global/audit/Auditable.java
server/src/main/java/team017/global/response/MultiResponseDto.java
server/src/main/java/team017/global/response/PageInfo.java
server/src/main/java/team017/global/response/SingleResponseDto.java
server/src/main/java/team017/security/config/WebMvcConfig.java

- Implement Auditable Class and WebMvcConfing Class.
- Refactoring package.

# 4 feat & refactor : implement and refactoring

---

server/src/main/java/team017/global/Exception/BusinessLogicException.java
server/src/main/java/team017/global/Exception/ExceptionCode.java

#11 feat: Exception 공통 클래스 초기 구현

---

server/src/main/java/team017/member/entity/Client.java
server/src/main/java/team017/member/entity/Member.java
server/src/main/java/team017/member/entity/SellHistory.java
server/src/main/java/team017/member/entity/Seller.java
server/src/main/java/team017/member/entity/SellerImage.java

- Member
- Client
- Seller
- SellerImage
- SellHistory

#14 feat: implement member domain entities

---

client/.prettierrc.json
client/GlobalStyles.js
client/src/assets/styles/GlobalStyles.js
client/src/index.js

#7 client  글로벌 색상 

---

server/build.gradle
server/src/main/java/team017/global/Exception/ExceptionCode.java
server/src/main/java/team017/member/controller/ClientController.java
server/src/main/java/team017/member/controller/SellerController.java
server/src/main/java/team017/member/dto/MemberDto.java
server/src/main/java/team017/member/entity/Member.java
server/src/main/java/team017/member/mapper/MemberMapper.java
server/src/main/java/team017/member/service/ClientService.java
server/src/main/java/team017/member/service/SellerService.java
server/src/main/java/team017/security/filter/JwtFilter.java
server/src/main/java/team017/security/handler/MemberAccessDeniedHandler.java
server/src/main/java/team017/security/handler/MemberAuthenticationEntryPoint.java
server/src/main/java/team017/security/handler/MemberAuthenticationFailureHandler.java
server/src/main/java/team017/security/handler/MemberAuthenticationSuccessHandler.java
server/src/main/java/team017/security/jwt/JwtProvider.java
server/src/main/java/team017/security/jwt/TokenDto.java
server/src/main/java/team017/security/service/MemberDetail.java
server/src/main/java/team017/security/service/MemberDetailService.java
server/src/main/resources/application.yml
server/src/test/java/team017/ServerApplicationTests.java
server/src/test/java/team017/member/ClientControllerTest.java
server/src/test/java/team017/member/MemberControllerTest.java

1. Dto Response 추가 
2. Service에서 조회 기능 추가
3. Jwt Provider 구현
4. Jwt Filter 구현
5. Jwt 인증 관련 핸들러 커스텀

#59 feat : jwt 관련 기능 구현 및 핸들러 커스텀

---

server/src/main/java/team017/board/Controller/BoardController.java
server/src/main/java/team017/board/Dto/BoardTotalResponseDto.java
server/src/main/java/team017/board/Entity/Board.java
server/src/main/java/team017/board/Mapper/BoardMapper.java
server/src/main/java/team017/board/Repository/BoardRepository.java
server/src/main/java/team017/board/Service/BoardService.java
server/src/main/java/team017/global/response/MultiResponseDto.java
server/src/main/java/team017/security/jwt/JwtProvider.java

판매글 전체 조회용 BoardTotalResponseDto 생성
#43 feat: 판매글 전체 조회 기능 구현 완료
#43 feat: 카테고리 별 조회 기능 구현 완료

#43 feat: 판매글 전체 조회 기능 + 카테고리 별 조회 기능 구현 완료

---

server/src/main/java/team017/board/Dto/BoardPatchDto.java
server/src/main/java/team017/board/Dto/BoardPostDto.java
server/src/main/java/team017/board/Dto/BoardResponseDto.java
server/src/main/java/team017/board/Dto/BoardTotalResponseDto.java
server/src/main/java/team017/board/Entity/Board.java
server/src/main/java/team017/image/Entity/Image.java
server/src/main/java/team017/image/Repository/ImageRepository.java
server/src/main/java/team017/product/Entity/Product.java
server/src/main/java/team017/product/Service/ProductService.java

- 이미지 테이블과 상품 테이블 연관관계 매핑 완료
- product 테이블 내 mainImage와 contentImage Read 구현 완료
- 태욱님께서 content 내 이미지와 텍스트 전송 기능 구현이 완료 되면 추가 수정 예정

#64 feat: 판매 게시글에서 이미지 불러오기 기능 구현

---

server/src/main/java/team017/global/Exception/ExceptionCode.java
server/src/main/java/team017/security/controller/SecurityController.java
server/src/main/java/team017/security/dto/LoginMapper.java
server/src/main/java/team017/security/dto/LoginResponse.java

fix: fix response

---

server/src/main/java/team017/security/controller/SecurityController.java
server/src/main/java/team017/security/dto/LoginMapper.java
server/src/main/java/team017/security/service/SecurityService.java

- 로그인 새로고침 응답 수정 
- 헤더 설정 코드 수정

#69 # 52 refactor : 로그인 응답 코드 및 헤더 리팩터링

---

server/src/main/java/team017/ord/controller/OrdController.java
server/src/main/java/team017/ord/dto/OrdPostDto.java
server/src/main/java/team017/ord/entity/Ord.java
server/src/main/java/team017/ord/mapper/OrdMapper.java
server/src/main/java/team017/ord/service/OrdService.java

#52 fix: fix ord domain

---

server/src/main/java/team017/kakaopay/Amount.java
server/src/main/java/team017/kakaopay/ApproveResponse.java
server/src/main/java/team017/kakaopay/KakaopayController.java
server/src/main/java/team017/kakaopay/KakaopayService.java
server/src/main/java/team017/kakaopay/Payment.java
server/src/main/java/team017/kakaopay/ReadyResponse.java
server/src/main/java/team017/product/Service/ProductService.java
server/src/main/java/team017/security/config/SecurityConfig.java
server/src/main/java/team017/security/config/WebMvcConfig.java
server/src/main/java/team017/security/controller/SecurityController.java
server/src/main/java/team017/security/controller/SocialController.java
server/src/main/java/team017/security/dto/SocialPatchDto.java
server/src/main/java/team017/security/service/KakaoService.java
server/src/main/java/team017/security/service/SecurityService.java
server/src/main/resources/application.yml

- 소셜 로그인 @Value 어노테이션 통해 yml 파일에서 불러오기
- 소셜 로그인 url 수정
- 소셜 로그인 권한 부여 추가
- 카카오 페이 결제 구현

#52 #69 #95 refactor & feat : 소셜 로그인 수정 및 카카오 페이 결제 구현

---

server/src/main/java/team017/ord/controller/OrdController.java
server/src/main/java/team017/ord/dto/OrdPostDto.java
server/src/main/java/team017/ord/dto/OrdResponseDto.java
server/src/main/java/team017/ord/entity/Ord.java
server/src/main/java/team017/ord/mapper/OrdMapper.java
server/src/main/java/team017/payment/Amount.java
server/src/main/java/team017/payment/ApproveResponseDto.java
server/src/main/java/team017/payment/KakaoPayService.java
server/src/main/java/team017/payment/PaymentController.java
server/src/main/java/team017/payment/ReadyResponseDto.java

실제 주문 내역 데이터 기반
결제 준비 -> 결제 승인 요청 -> 결제 완료 기능 구현 완료

#21 #95 feat: 실제 주문 내역 기반 결제 기능 구현 완료+ fix: order post 기능 수정

---

server/build.gradle
server/src/main/java/team017/ServerApplication.java
server/src/main/java/team017/global/aop/ReissueToken.java
server/src/main/java/team017/global/aop/SecurityAspect.java
server/src/main/java/team017/member/controller/MemberController.java
server/src/main/java/team017/member/dto/MemberDto.java
server/src/main/java/team017/member/mapper/MemberMapper.java
server/src/main/java/team017/security/config/SecurityConfig.java
server/src/main/java/team017/security/controller/SecurityController.java
server/src/main/java/team017/security/controller/SocialController.java
server/src/main/java/team017/security/dto/LoginRequestDto.java
server/src/main/java/team017/security/dto/LoginResponse.java
server/src/main/java/team017/security/service/SecurityService.java

#69 feat : aop token 재발급 구현 및 자동로그인 시도

---

server/src/main/java/team017/board/Dto/BoardForSellerMyPageDto.java
server/src/main/java/team017/board/Dto/BoardResponseDto.java
server/src/main/java/team017/board/Dto/BoardTotalResponseDto.java
server/src/main/java/team017/board/Entity/Board.java
server/src/main/java/team017/board/Repository/BoardRepository.java
server/src/main/java/team017/board/Service/BoardService.java
server/src/main/java/team017/ord/controller/OrdController.java
server/src/main/java/team017/ord/dto/OrdPostDto.java
server/src/main/java/team017/ord/dto/OrdResponseDto.java
server/src/main/java/team017/ord/entity/Ord.java
server/src/main/java/team017/ord/mapper/OrdMapper.java
server/src/main/java/team017/ord/service/OrdService.java

- #21 fix: Ord 주문 생성 및 주문 삭제 기능 구현 수정
- #66 feat: 잔여 재고 수량 표시 기능 구현 완료

#21 #66 feat: Ord 기능구현 수정 + 판매 게시글 추가 기능 구현 완료

---

server/src/main/java/team017/member/entity/Seller.java
server/src/main/java/team017/ord/entity/Ord.java
server/src/main/java/team017/payment/KakaoPayService.java
server/src/main/java/team017/payment/ReadyResponseDto.java

- https://github.com/codestates-seb/seb40_main_017/issues/108 [fix: 연관관계 매핑 수정](https://github.com/codestates-seb/seb40_main_017/commit/d2d489f10dbd38f0be508f2331eaa80c35bf102b) : seller, order 연관관계 주석 삭제
- https://github.com/codestates-seb/seb40_main_017/issues/66 [feat: 주문,결제 실패 시 잔여 수량 변경 기능 구현](https://github.com/codestates-seb/seb40_main_017/commit/da93c4d744a651408da451391946b193c9eec9a3): 주문, 결제 실패 시 원래 잔여 수량으로 돌아감

#66 feat: 주문,결제 실패 시 잔여 수량 변경 기능 구현

---

server/src/main/java/team017/member/controller/SellerController.java
server/src/main/java/team017/member/service/MemberService.java
server/src/main/java/team017/member/service/SellerService.java

#118 add seller log

---

server/src/main/java/team017/member/controller/ClientController.java
server/src/main/java/team017/member/controller/MemberController.java
server/src/main/java/team017/member/mapper/MemberMapper.java
server/src/main/java/team017/member/service/ClientService.java
server/src/main/java/team017/member/service/SellerService.java

- 로그인한 클라이언트가 일치하는지 확인하는 메서드 추가
- 로그인한 셀러가 일치하는지 확인하는 메서드 추가

#52 #120 feat: 현재 로그인 유저와 url 유저의 일치 판별 메서드 추가 및 컨트롤러 수정

---

server/src/main/java/team017/member/controller/ClientController.java
server/src/main/java/team017/member/service/SellerService.java

- seller 메서드 수정 및 controller 토큰 수정

#52 fix: 수정

---

server/src/main/java/team017/member/controller/SellerController.java
server/src/main/java/team017/security/config/SecurityConfig.java
server/src/main/java/team017/security/jwt/SecurityProvider.java
server/src/main/java/team017/security/oauth/service/KakaoService.java

- config 주석 및 안되었던 부분 추가 -> 확인 위해 남은 인증 부분 어드민으로 설정  -> 배포시에는 수정할 예정

#52 fix: token and config 관련 수정

---

server/src/main/java/team017/ord/entity/Ord.java
server/src/main/java/team017/ord/mapper/OrdMapper.java
server/src/main/java/team017/ord/service/OrdService.java

#21 fix: Ord mapper 수정

---

server/src/main/java/team017/member/controller/SocialController.java
server/src/main/java/team017/security/oauth/service/KakaoService.java

#118 [로그 추가](add: add log to find error)

#118 add: add log to find error

---

server/build.gradle
server/src/main/java/team017/member/controller/SocialController.java
server/src/main/java/team017/security/oauth/service/KakaoService.java

#69 fix: kakao login

---

server/src/main/java/team017/member/controller/SocialController.java
server/src/main/java/team017/member/entity/Member.java
server/src/main/java/team017/security/jwt/service/SecurityService.java
server/src/main/java/team017/security/oauth/service/KakaoService.java

#52 #69 refactoring for kakao server login.....!!!! 😡😡😡😡

#52 #69 refactor: for kakao server login

---

server/src/main/java/team017/member/controller/ClientController.java
server/src/main/java/team017/member/controller/SellerController.java
server/src/main/java/team017/security/jwt/TokenController.java

#52 delete: 토큰 재발급 삭제

---

server/src/main/java/team017/ServerApplication.java
server/src/main/java/team017/mail/EmailService.java
server/src/main/java/team017/mail/EmailServiceImpl.java
server/src/main/java/team017/member/controller/ClientController.java
server/src/main/java/team017/member/controller/MemberController.java
server/src/main/java/team017/member/controller/SellerController.java
server/src/main/java/team017/member/controller/SocialController.java
server/src/main/java/team017/member/dto/MemberDto.java
server/src/main/java/team017/member/entity/Client.java
server/src/main/java/team017/member/entity/Member.java
server/src/main/java/team017/member/entity/Seller.java
server/src/main/java/team017/member/mapper/MemberMapper.java
server/src/main/java/team017/member/repository/MemberRepository.java
server/src/main/java/team017/security/config/SecurityConfig.java
server/src/main/java/team017/security/jwt/TokenController.java
server/src/main/java/team017/security/jwt/dto/LoginRequestDto.java
server/src/main/java/team017/security/jwt/dto/TokenDto.java
server/src/main/java/team017/security/jwt/handler/MemberAuthenticationEntryPoint.java
server/src/main/java/team017/security/jwt/handler/MemberAuthenticationFailureHandler.java
server/src/main/java/team017/security/jwt/refresh/RefreshToken.java
server/src/main/java/team017/security/jwt/refresh/RefreshTokenRepository.java
server/src/main/java/team017/security/jwt/service/MemberPrincipalService.java
server/src/main/java/team017/security/jwt/service/SecurityService.java
server/src/main/java/team017/security/oauth/dto/SocialPatchDto.java
server/src/main/java/team017/security/oauth/handler/OAuth2FailureHandler.java
server/src/main/java/team017/security/oauth/service/KakaoService.java

#52 메일 이미지 발송으로 수정 및 안쓰는 주석과 import 삭제

#52 메일 이미지 발송으로 수정 및 안쓰는 주석과 import 삭제

---

server/src/main/java/team017/ord/dto/OrdPostDto.java
server/src/main/java/team017/ord/dto/OrdResponseDto.java
server/src/main/java/team017/ord/dto/OrdSellerResponseDto.java
server/src/main/java/team017/payment/KakaoPayService.java
server/src/main/java/team017/payment/PaymentController.java
server/src/main/java/team017/product/Service/ProductService.java

- https://github.com/codestates-seb/seb40_main_017/issues/52 [refactor: 코드 주석 제거](https://github.com/codestates-seb/seb40_main_017/commit/1d43f054ae545ad1faaa0af40cdcbf3f5dd71816)
- https://github.com/codestates-seb/seb40_main_017/issues/43 [fix: product 내mainImage 수정 코드 추가](https://github.com/codestates-seb/seb40_main_017/commit/285f2b971396668bfe4e7c5875d6f21bc57ca53b)

#52 refactor: 코드 주석 제거

---

server/src/main/java/team017/security/oauth/service/KakaoService.java

#52 fix: 이모지 삭제

---

server/src/main/java/team017/security/config/WebMvcConfig.java

#52 Cors를 위해 특정 주소만 허용
- 만일 효과가 없다면 다시 돌아갈 예정

#52 refactor: 특정 주소만 허용

---

server/src/main/java/team017/security/oauth/service/KakaoService.java

#52 #69 refactor : 이모지 지우기 제거 및 널값 이름 시 디폴트값 추가

---

client/src/components/Comment.js
client/src/components/CommentElement.js
client/src/components/Review.js
client/src/components/ReviewElement.js
client/src/components/StarRate.js
client/src/pages/CropsListPage.js
client/src/pages/crops/CropInfoPage.js
client/src/pages/crops/FruitsPage.js
client/src/pages/crops/GrainPage.js
client/src/pages/crops/NutsPage.js
client/src/pages/crops/VegetablePage.js

+) console.log 삭제, 게시판 css 수정, 상세페이지 내용 크기조절

[client] #219 Fix: 댓글,문의 삭제가안되는오류

---

server/src/main/java/team017/global/Exception/ExceptionCode.java
server/src/main/java/team017/ord/repository/OrdRepository.java
server/src/main/java/team017/review/service/ReviewService.java

https://github.com/codestates-seb/seb40_main_017/issues/218 [feat: 주문한 사람만 리뷰 작성 가능하게 기능 추가](https://github.com/codestates-seb/seb40_main_017/commit/ceeed95f94f9c8e5b4922c3fadc91e3b5a55d44f)

#218 feat: 주문한 사람만 리뷰 작성 가능하게 기능 추가

---

server/src/main/java/team017/comments/entity/Comment.java
server/src/main/java/team017/member/entity/Member.java

#205 comment - member 연관관계 수정 : 멤버 탈퇴 가능?

#205 refactor : comment - member 연관관계 수정

---

server/src/main/java/team017/global/Exception/ExceptionCode.java
server/src/main/java/team017/ord/repository/OrdRepository.java
server/src/main/java/team017/review/service/ReviewService.java

#205 refactor : 구매한 사람만 리뷰 작성 가능하게 수정
